name: pasos_package
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/vigoco/pasos_package


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  pedometer: ^4.1.1
  async: ^2.11.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

